# Generated by Django 3.2.6 on 2022-05-11 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Административный округ')),
            ],
            options={
                'verbose_name': 'Административный округ',
                'verbose_name_plural': 'Административные округа',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория объекта культурного наследия',
                'verbose_name_plural': 'Категории объектов культурного наследия',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название района')),
            ],
            options={
                'verbose_name': 'Район Москвы',
                'verbose_name_plural': 'Районы Москвы',
            },
        ),
        migrations.CreateModel(
            name='StatusObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус объекта')),
            ],
            options={
                'verbose_name': 'Категория объекта культурного наследия',
                'verbose_name_plural': 'Категории объектов культурного наследия',
            },
        ),
        migrations.CreateModel(
            name='TypeObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа объекта')),
            ],
            options={
                'verbose_name': 'Тип объекта культурного наследия',
                'verbose_name_plural': 'Типы объектов культурного наследия',
            },
        ),
        migrations.CreateModel(
            name='CultureObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('ensemble_name_on_doc', models.CharField(max_length=255, verbose_name='Название объекта в документах')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('addresses', models.CharField(max_length=255, verbose_name='Адрес')),
                ('long_position', models.DecimalField(decimal_places=13, max_digits=15, null=True)),
                ('lat_position', models.DecimalField(decimal_places=13, max_digits=15, null=True)),
                ('adm_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.admarea')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.district')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.statusobject')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.typeobject')),
            ],
            options={
                'verbose_name': 'Объект культурного наследия',
                'verbose_name_plural': 'Объекты культурного наследия',
            },
        ),
    ]
