# Generated by Django 3.2.6 on 2022-05-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultureobject',
            name='adm_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.admarea', verbose_name='Административный округ'),
        ),
        migrations.AlterField(
            model_name='cultureobject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория объекта'),
        ),
        migrations.AlterField(
            model_name='cultureobject',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.district', verbose_name='Район Москвы'),
        ),
        migrations.AlterField(
            model_name='cultureobject',
            name='lat_position',
            field=models.DecimalField(decimal_places=13, max_digits=15, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='cultureobject',
            name='long_position',
            field=models.DecimalField(decimal_places=13, max_digits=15, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='cultureobject',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.statusobject', verbose_name='Статус объекта'),
        ),
        migrations.AlterField(
            model_name='cultureobject',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.typeobject', verbose_name='Тип объекта'),
        ),
    ]
